### ISSUE TITLE
[BUG] Display error message if finding a circular dependency

### ISSUE THREAD

**Issue by stephanboersma** [stephanboersma/react-bratus#21]
**Describe the bug**
Parsing crashes if a circular dependency is found

**To Reproduce**
Having a circular dependency in the code:

RegisterForm.js
```
const RegisterForm = () => {
    return <FormField />
}

const FormField = () => {
    return <Modal isOpen={isOpen}><RegisterForm /></Modal>
}
```

**Expected behavior**
An error message should be displayed to the end-user.

**Comment by mircealungu** [comment]
eheh. heard about this from Sara :)

**Comment by stephanboersma** [comment]
Yeah, not entirely sure how to fix this one. haha haha
